### ISSUE TITLE
Inverse relation with List

### ISSUE THREAD

**Issue by tavoda** [sculptor/sculptor#205]
Declaration for inverse relation with List doesn't generate mappedBy field of @OneToMany annotation. @tjuerge do you know what is problem with List? For Set it's generated OK. Responsible for this is [line 375 in DomainObjectReferenceAnnotationTmpl.xtend](https://github.com/sculptor/sculptor/blob/c69d2612036412b37560abc0be1fcafd8d079462/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectReferenceAnnotationTmpl.xtend#L375
). RefCollection have to be different that 'list'. We have to fix it here, I don't know why it can't work with List or we have to fix it in SQL generator because now it generates SQL for foreign ref instead of separate rel table (like N:M).

**Comment by tjuerge** [comment]
The check [`«IF !isMappedBy»`](https://github.com/sculptor/sculptor/blob/c69d2612036412b37560abc0be1fcafd8d079462/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectReferenceAnnotationTmpl.xtend#L384) was introduced in #168 in [commit #9e92356b6068](https://github.com/sculptor/sculptor/commit/9e92356b6068a818b314e1f09edbd38e002b65ac#diff-bb26512e21b57f41d248e55accf249e2L385). I don't know why I had to add this check at that time - maybe due to a failing test or example.

Please add a corresponding test in the test suite (e.g. in `DomainObjectReferenceAnnotationTmplDDDSampleTest.xtend`) and try to remove the check.

**Comment by tjuerge** [comment]
The check [`«IF !isMappedBy»`](https://github.com/sculptor/sculptor/blob/c69d2612036412b37560abc0be1fcafd8d079462/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectReferenceAnnotationTmpl.xtend#L384) was needed because otherwise a Hibernate `AnnotationException: Associations marked as mappedBy must not define database mappings like @JoinTable or @JoinColumn` is thrown.

The exclusion of the list collection type is a [heritage from previous Sculptor versions](https://github.com/sculptor/base/blob/4c17bbd86a5bfb7bb66226e95ccc6e8f6a70bcea/sculptor-generator/src/main/resources/templates/domain/DomainObjectReferenceAnnotation.xpt#L376). It seem's that [at those days Hibernate's List type was not the favorite one](https://www.mail-archive.com/fornax-developer@lists.sourceforge.net/msg00814.html) :-)

> The reason is that we didn't find it very useful to use List for that type of association.

**Comment by tjuerge** [comment]
Maybe the exclusion of Hibernate's list type was due to issues or inefficiencies (like the ones described in [How to Choose the Most Efficient Data Type for To-Many Associations – Bag vs. List vs. Set](https://thoughts-on-java.org/association-mappings-bag-list-set/)).

**Comment by tavoda** [comment]
Maybe we can mention this in documentation and it's user choice to use List. But code is generated correctly and it's working. With this check we generate WRONG code.

**Comment by tjuerge** [comment]
> With this check we generate WRONG code.

Ok, without the check [`«IF !isMappedBy»`](https://github.com/sculptor/sculptor/blob/c69d2612036412b37560abc0be1fcafd8d079462/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectReferenceAnnotationTmpl.xtend#L384) maybe the code is correct. But it's not accepted by Hibernate - our own examples are throwing `AnnotationException: Associations marked as mappedBy must not define database mappings like @JoinTable or @JoinColumn`.

**Comment by tjuerge** [comment]
Please add a corresponding test (for the intended behaviour) in the test suite (e.g. in `DomainObjectReferenceAnnotationTmplDDDSampleTest.xtend`) and try to remove the check [`«IF !isMappedBy»`](https://github.com/sculptor/sculptor/blob/c69d2612036412b37560abc0be1fcafd8d079462/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectReferenceAnnotationTmpl.xtend#L384).

**Comment by tavoda** [comment]
In DomainObjectReferenceAnnotationTmplDDDSampleTest I introduced new test assertAllPersonReferences() with all type of relations which I can imagine in new model model-relations.btdesign. It never generate mappedBy with JoinTable or JoinColumn together. @tjuerge which samples are throwing error? Everything run fine, all tests are OK.

**Comment by tjuerge** [comment]
>which samples are throwing error? Everything run fine, all tests are OK.

I was refering to  [`«IF !isMappedBy»`](https://github.com/sculptor/sculptor/blob/c69d2612036412b37560abc0be1fcafd8d079462/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectReferenceAnnotationTmpl.xtend#L384) introduced by me and not to the clause `&& (getRefCollectionType() != "list")`   :-P

The `&& (getRefCollectionType() != "list")` is part of former Sculptor versions (version 2 and older), e.g. available [here](https://github.com/sculptor/base/blob/4c17bbd86a5bfb7bb66226e95ccc6e8f6a70bcea/sculptor-generator/src/main/resources/templates/domain/DomainObjectReferenceAnnotation.xpt#L376). And I've no clue why this exclusion of Hibernate's list type was necessary these days.

**Comment by tavoda** [comment]
Aha, OK, I didn't checked older versions. Maybe it was problem with older version of Hibernete, plus we was using hibernate specific annotations which are removed now and except performance hit it's working. We can document this but we can't prohibit List(s).
I'm writing new tests for DDDSample in example project (different DDDSample than it's in template project). I found another bug but I will open new ticket for this. Closing, TNX.
