### ISSUE TITLE
Allow override for Transformation

### ISSUE THREAD

**Issue by tavoda** [sculptor/sculptor#217]
It's very useful to have possibility to override transformation phase.
We had problem with Xtend annotation processor when Transformation was annotated with our extension mechanism for overriding (@ChainOverridable). It looks like new version is working for Transformation phase.

**Comment by tjuerge** [comment]
Are you sure that the issues raised in #64 ([`@ChainOverridable`'s caches implemented as private members named `_createCache_<method name>_<counter>`](https://github.com/sculptor/sculptor/issues/64#issuecomment-77061562)) are gone now?

**Comment by tavoda** [comment]
I just make some basic tests and it's working. How to test this? Is it only
for create methods?

/Palo

**Comment by tjuerge** [comment]
>How to test this?

With the test case `DslTransformationTest.testServiceDependency()` in the feature branch [feature/transformation-override](https://github.com/sculptor/sculptor/tree/feature/transformation-override) this issue (here [the same module is created multiple times](https://travis-ci.org/sculptor/sculptor/builds/642042232#L6874)) can be tested in isolation.

**Comment by tjuerge** [comment]
> Is it only for create methods?

No, it's related to state in general (explicitly via member variables or implicitly via the create methods cache implementation).

Quote from [comment](https://github.com/sculptor/sculptor/issues/64#issuecomment-77061562) in #64:

> Using `@ChainOverridable` on Xtend classes which are maintaining state (explicitly via member variables or implicitly via the create methods cache implementation) leads to strange errors like this.
This is due to the inheritance hierarchy created by Sculptors active annotation processor and maintaining separate instances: The instance of the overriding class has it's state (via extending the class annotated with `@ChainOverridable`) and the instance of the overridable class has it's state. Calling methods on the overriding class or the overridable class manipulates the state within separate instances of the annotated class. With create methods this leads to creation of multiple instances due to separate caches implemented as private members named `_createCache_<method name>_<counter>`.
