### ISSUE TITLE
IDTYPE and UUID

### ISSUE THREAD

**Issue by stefan-ka** [sculptor/sculptor#227]
In your documentation you feature IDTYPE and UUID as default built-in types of your DSL: 
http://sculptorgenerator.org/documentation/advanced-tutorial#attributes-and-references

However, it seems like your Xtext grammar does not support that types, right?
Is it planned to add them to the language or is this an error in the documentation?

**Comment by tjuerge** [comment]
Both types are internally used domain object attributes which are automatically added during [model transformation](http://sculptorgenerator.org/documentation/developers-guide#model-enrichment).

The [UUID](http://sculptorgenerator.org/documentation/advanced-tutorial#key) is used in the generated implementation of `equals()` and `hashCode()`. With the DSL keyword "key" domain object attributes can be marked for being used as natural key(s) instead of the default implementation `java.util.UUID.randomUUID()`.

The [IDTYPE](http://sculptorgenerator.org/documentation/advanced-tutorial#id) is used as surrogate primary key for persistent objects. There is no DSL keyword available because this attribute is purely technical. Only it's datatype (default `Long`) can be modified via [generator configuration](http://sculptorgenerator.org/documentation/developers-guide#types).

**Comment by stefan-ka** [comment]
Thanks for the quick answer! That's fine for me...
